name: mysqlCluster
modulepath: libs
downloadpath: libs
description: deploy MySQL cluster in master-slave setup
requires:
    std: git@github.com:impera-io/std, ">= 0.1"
    net: git@github.com:impera-io/net, ">= 0.1"
    ip: git@github.com:impera-io/ip, ">= 0.1"
    redhat: git@github.com:impera-io/redhat, ">= 0.1"
    mysqlCluster: git@github.com:arnaudsjs/imp-mysqlCluster, ">= 0.1"
