#!/bin/python

import os;

USERNAME_SLAVE = "slave_user";
PASSWORD_SLAVE_USER = "slave_user";
CLUSTER_MEMBER_CONFIG = "/etc/sysconfig/mysqlCluster";
DATABASES_CONFIG = "/etc/sysconfig/mysql";

#TESTED
def updateMembership():
	createSlaveUserWithReplicationRights();
	slavesInConfig = getEntriesInConfigFile("slave", CLUSTER_MEMBER_CONFIG);
	if (len(slavesInConfig) > 0):
		sendRequiredDataToSlaves(slavesInConfig);

#TESTED
def sendRequiredDataToSlaves(slaves):
	sendDatabaseDumpsToSlaves(slaves);
	sendMasterStatusToSlaves(slaves);

#TESTED
def sendDatabaseDumpsToSlaves(slaves):
	databaseNames = getEntriesInConfigFile("hasdb", DATABASES_CONFIG);
	for name in databaseNames:
		path = "/tmp/" + name + ".sql";
		command = "USE " + name + ";";
		command += "FLUSH TABLES WITH READ LOCK;";
		command += "SYSTEM mysqldump -u root --opt " + name + " > " +  path + ";";
		command += "UNLOCK TABLES;";
		executeCommandInMysqlShell(command);
		sendToAllSlaves(path, path, slaves);

#TESTED
def sendMasterStatusToSlaves(slaves):
	command = "SHOW MASTER STATUS\G";
	output = executeCommandInMysqlShell(command);
	binLog = findEntryInMasterStatus(output, "File");
	position = findEntryInMasterStatus(output, "Position");
	path = "/tmp/master_status";
	writeStringToFile(path, binLog + "&" + position);
	sendToAllSlaves(path, path, slaves);

#TESTED
def writeStringToFile(path, content):
	fileStream = open(path,"w");
	fileStream.write(content);
	fileStream.close();

#TESTED
def findEntryInMasterStatus(status, section):
	entries = status.split("\n");
	for entry in entries:
		if (entry.find(section) != -1):
			result = entry.strip("\n ");
			result = result.split(":")[1];
			return result.strip(" ");
	raise "Section not found in status", section;

#TESTED	
def sendToAllSlaves(localPath, remotePath, ips):
	for ip in ips:
		sendToSlave(localPath, remotePath, ip);

#TESTED
def sendToSlave(localPath, remotePath, slaveIp):
	os.popen("scp " + localPath + " root@" + slaveIp + ":" + remotePath);

#TESTED
def getEntriesInConfigFile(label, pathToConfigFile):
	filestream = open(pathToConfigFile,"r");
	result = set();
	for line in filestream:
		if (line.find(label) != -1):
			line = line.strip("\n ");
			resultItem = line.split(" ")[1];
			resultItem = resultItem.strip(" ");
			result.add(resultItem);
	filestream.close();
	return result;

#TESTED
# This operation is idempotent
def createSlaveUserWithReplicationRights():
	grantCommand = "GRANT REPLICATION SLAVE ON *.* TO '" + USERNAME_SLAVE + "'@'%' IDENTIFIED BY '" + PASSWORD_SLAVE_USER  + "';";
	flushCommand = "FLUSH PRIVILEGES;";
	executeCommandInMysqlShell(grantCommand);
	executeCommandInMysqlShell(flushCommand);

#TESTED
def executeCommandInMysqlShell(mysqlCommand):
	shellCommand = "/usr/bin/mysql -uroot -s -e \"" + mysqlCommand  + "\"";
	return os.popen(shellCommand).read();

updateMembership();